###
POST http://localhost:8080/event/create
Content-Type: application/json

{
  "type": "RequestEventCreate",
  "requestId": "1",
  "event": {
    "name": "name",
    "description": "description",
    "startSchedule": "2021-02-25T13:40:00",
    "userId": "userId",
    "frequency": "YEARLY",
    "mobile": "7123456789"
  }
}

###
POST http://localhost:8080/event/read
Content-Type: application/json

{
  "type": "RequestEventRead",
  "requestId": "1",
  "eventId": "76f842ab-ddba-4176-97f9-e31c37c5352c"
}

###
POST http://localhost:8080/event/update
Content-Type: application/json

{
  "type": "RequestEventUpdate",
  "requestId": "1",
  "event": {
    "id": "76f842ab-ddba-4176-97f9-e31c37c5352c",
    "name": "name",
    "description": "description",
    "startSchedule": "2022-02-25T13:40:00",
    "userId": "userId",
    "frequency": "YEARLY",
    "mobile": "7123456789"
  }
}

###
POST http://localhost:8080/event/delete
Content-Type: application/json

{
  "type": "RequestEventDelete",
  "requestId": "1",
  "eventId": "76f842ab-ddba-4176-97f9-e31c37c5352c"
}

###
POST http://localhost:8080/event/filter
Content-Type: application/json

{
  "type": "RequestEventFilter",
  "requestId": "1",
  "filter": {
    "frequency": "YEARLY",
    "from": "0",
    "pageSize": "2"
  }
}

