###
POST http://localhost:8080/event/create
Content-Type: application/json

{
  "type": "RequestEventCreate",
  "requestId": "1",
  "event": {
    "name": "name",
    "description": "description",
    "startSchedule": "startSchedule",
    "userId": "userId",
    "frequency": "YEARLY",
    "mobile": "7123456789"
  }
}

###
POST http://localhost:8080/event/read
Content-Type: application/json

{
  "type": "RequestEventRead",
  "requestId": "1",
  "eventId": "event-id"
}

###
POST http://localhost:8080/event/update
Content-Type: application/json

{
  "type": "RequestEventUpdate",
  "requestId": "1",
  "event": {
    "id": "id",
    "name": "name",
    "description": "description",
    "startSchedule": "startSchedule",
    "userId": "userId",
    "frequency": "YEARLY",
    "mobile": "7123456789"
  }
}

###
POST http://localhost:8080/event/delete
Content-Type: application/json

{
  "type": "RequestEventDelete",
  "requestId": "1",
  "eventId": "event-id"
}

###
POST http://localhost:8080/event/filter
Content-Type: application/json

{
  "type": "RequestEventFilter",
  "requestId": "1",
  "filter": {
    "frequency": "YEARLY",
    "from": "10",
    "pageSize": "2"
  }
}

